# 插件设置，谨慎修改！
INFO:
  Author: NekokeCore
  PluginsVersion: 1.3
  ConfigVersion: 1.1

MySql:
  Enable: false
  UseSSL: false
  Address: 127.0.0.1
  User: root
  Passwords: root
  Database: mysql

PlayerListener:
  Enable: true
WorldListener:
  Enable: true
BlockListener:
  Enable: true